name: Ubuntu (build-&-test)

on:
  push:
    branches:
      - devel
  pull_request:
    branches:
      - devel

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install Unix dependencies
        run: |
          sudo apt-get install time libunwind8-dev g++-9 gcc-9 git
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 90 --slave /usr/bin/g++ g++ /usr/bin/g++-9 --slave /usr/bin/gcov gcov /usr/bin/gcov-9

      - name: Initialize Git
        run: |
          git config --global user.email "perun-allmighty@gmail.com"
          git config --global user.name "Perun Allmighty"

      - name: Upgrade pip and setuptools dependencies
        run: |
          python -m pip install --upgrade pip setuptools

      - name: Install Tox
        run: |
          pip install tox

      - name: Execute tests for Python ${{ matrix.python-version }} using Tox
        run: tox -e py

      - name: Generate docs for Python ${{ matrix.python-version }} using Tox
        run: |
          tox -e docs

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: coverage-${{ matrix.python-version }}
          verbose: true